name: 工作日股票資料下載

on:
  schedule:
    # 週一到週五下午 18:00 執行 (UTC 時間 10:00，台灣時間為 18:00)
    - cron: "00 10 * * 1-5"
  workflow_dispatch:

jobs:
  download-weekday-data:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 設定 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: 安裝依賴
        run: npm ci

      - name: 更新套件列表並安裝系統依賴
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libasound2-dev

      - name: 安裝 Playwright 瀏覽器
        run: npx playwright install chromium

      - name: 執行工作日股票資料下載
        run: node -e "require('./app.js').downloadStockDataWeekday()"

      - name: 上傳檔案到 Google Drive
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: node upload-to-drive.js

      - name: 清理下載檔案
        run: rm -rf */

